Repository woowa-techcamp-2021/store-1, pull requests merged in 2021-08, with the labels that each got.

#2 📝 docs: template 추가
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitmessage
Labels: docs

#5 [feature/#4] 기본적인 설정파일 추가
  .gitignore
  client/.devcontainer/Dockerfile
  client/.devcontainer/devcontainer.json
  client/.editorconfig
  client/.prettierrc
  server/.devcontainer/Dockerfile
  server/.devcontainer/devcontainer.json
  server/.devcontainer/docker-compose.yml
  server/.editorconfig
  server/.prettierrc
Labels: feature

#8 [docs/#3] README
  README.md
Labels: docs

#9 [feature/#6] frontend 환경 설정
  client/babel.config.js
  client/package.json
  client/public/index.html
  client/src/components/App.tsx
  client/src/main.tsx
  client/test/App.test.tsx
  client/test/index.js
  client/test/transform/babelTransform.js
  client/test/transform/cssTransform.js
  client/test/transform/fileTransform.js
  client/tsconfig.json
  client/webpack.config.ts
  client/webpack/webpack.config.common.ts
  client/webpack/webpack.config.dev.ts
  client/webpack/webpack.config.prod.ts
  client/yarn.lock
Labels: feature

#12 [feature/#10] react router
  client/package.json
  client/src/App.tsx
  client/src/components/App.tsx
  client/src/components/Nav.tsx
  client/src/context/index.ts
  client/src/hooks/useHistory.tsx
  client/src/hooks/useRouter.tsx
  client/src/main.tsx
  client/src/pages/Error404.tsx
  client/src/pages/Home.tsx
  client/src/pages/Signin.tsx
  client/src/pages/User.tsx
  client/src/router/Link.tsx
  client/src/router/NavLink.tsx
  client/src/router/Route.tsx
  client/src/router/Router.tsx
  client/src/router/history.ts
  client/src/types/history.d.ts
  client/test/App.test.tsx
  client/tsconfig.json
  client/webpack/webpack.config.common.ts
  client/yarn.lock
Labels: feature

#15 [feature#13] styled-component global style 적용
  client/package.json
  client/src/App.tsx
  client/src/styles/global-style.ts
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
  client/yarn.lock
Labels: feature

#23 📝 docs: Co-author 추가
  .gitmessage
Labels: docs

#22 [feature/#20] 스타일드 컴포넌트
  client/.devcontainer/devcontainer.json
  client/package.json
  client/src/App.tsx
  client/src/lib/styled-components/index.tsx
  client/src/lib/styled-components/tag-names.ts
  client/src/lib/styled-components/utils.ts
  client/src/pages/Home.tsx
  client/src/pages/Signin.tsx
  client/src/pages/SignupMethod.tsx
  client/src/styles/global-style.ts
  client/src/styles/theme.ts
  client/src/types/styled.d.ts
  client/tsconfig.json
  client/webpack/webpack.config.common.ts
  client/yarn.lock
Labels: feature

#34 [Feature/#33] 회원가입 페이지
  .gitmessage
  client/package.json
  client/src/App.tsx
  client/src/components/Signup/Address.tsx
  client/src/components/Signup/Agreement.tsx
  client/src/components/Signup/FormElement.tsx
  client/src/pages/Signin.tsx
  client/src/pages/Signup.tsx
  client/src/styles/global-style.ts
  client/yarn.lock
Labels: feature

#37 [feature/#30] Carousel 구현
  client/src/assets/images/banner_one.gif
  client/src/assets/images/banner_three.gif
  client/src/assets/images/banner_two.gif
  client/src/components/Carousel.tsx
  client/src/pages/Home.tsx
Labels: feature

#41 [feature/#24] React-Router path params 기능 추가
  client/package.json
  client/src/App.tsx
  client/src/context/index.ts
  client/src/hooks/useHistory.tsx
  client/src/hooks/useParams.tsx
  client/src/hooks/usePath.tsx
  client/src/hooks/useRouter.tsx
  client/src/lib/router/BrowserRouter.tsx
  client/src/lib/router/Link.tsx
  client/src/lib/router/NavLink.tsx
  client/src/lib/router/Route.tsx
  client/src/lib/router/Router.tsx
  client/src/lib/router/Switch.tsx
  client/src/lib/router/history.ts
  client/src/lib/router/match-path.ts
  client/src/pages/Category.tsx
  client/src/types/history.d.ts
  client/tsconfig.json
Labels: feature

#61 [bugfix/#47] history.state 없으면 초기상태 주입
  client/src/lib/router/history.ts
Labels: bug

#75 [refactor/#74] product list에서 item 컴포넌트 분리
  client/src/components/Nav/Category.tsx
  client/src/components/ProductList.tsx
  client/src/components/ProductListItem.tsx
  client/src/pages/Home.tsx
Labels: refactor

#83 [fix/#82] router 버그 수정
  client/src/lib/router/history.ts
Labels: bug

#88 [feature/#87] NavLink에 search와 hash도 추가
  client/src/lib/router/NavLink.tsx
  client/src/lib/router/history.ts
Labels: bug, feature

#89 [Feature/#39] 마이페이지 및 리팩토링
  client/src/App.tsx
  client/src/components/MyPage/FormElementWithoutInput.tsx
  client/src/components/MyPage/MenuBar.tsx
  client/src/components/Signup/Agreement.tsx
  client/src/components/common/Address.tsx
  client/src/components/common/ButtonNext.tsx
  client/src/components/common/ButtonPrev.tsx
  client/src/components/common/FormElement.tsx
  client/src/pages/MyPage/MyPage.tsx
  client/src/pages/MyPage/MyPageConfirm.tsx
  client/src/pages/MyPage/MyPageEdit.tsx
  client/src/pages/Signup/Signup.tsx
  client/src/pages/Signup/SignupMethod.tsx
  client/src/pages/User.tsx
  client/tsconfig.json
  client/webpack/webpack.config.common.ts
Labels: feature

#93 [feature/#92] 이용약관, 개인정보처리방침 페이지
  client/src/App.tsx
  client/src/constants/terms.ts
  client/src/pages/Terms.tsx
Labels: feature

#90 [feature/#81] category page
  client/package.json
  client/public/index.html
  client/src/App.tsx
  client/src/components/Error.tsx
  client/src/components/Pagination.tsx
  client/src/components/Sort.tsx
  client/src/hooks/query/products/index.tsx
  client/src/lib/api/product/index.ts
  client/src/pages/Category.tsx
  client/webpack/webpack.config.dev.ts
  client/yarn.lock
Labels: feature

#103 [feature/#96] 장바구니 페이지 컴포넌트
  client/src/App.tsx
  client/src/components/ExitBtn.tsx
  client/src/components/Nav/CartButton.tsx
  client/src/components/Nav/Nav.tsx
  client/src/hooks/useLocalStorage.tsx
  client/src/pages/Cart.tsx
  client/src/styles/theme.ts
  client/src/types/index.ts
  client/src/types/styled.d.ts
  client/tsconfig.json
  client/webpack/webpack.config.common.ts
Labels: feature

#107 [refactor/#104] product, cart 타입 변경
  client/src/components/Nav/CartButton.tsx
  client/src/components/ProductList.tsx
  client/src/components/ProductListItem.tsx
  client/src/pages/Cart.tsx
  client/src/pages/Home.tsx
  client/src/types/index.ts
Labels: refactor

#109 [feature/#100] toastify
  client/package.json
  client/public/index.html
  client/src/App.tsx
  client/src/components/Toastify/Portal.tsx
  client/src/components/Toastify/ToastifyContainer.tsx
  client/src/lib/toastify/index.tsx
  client/webpack/webpack.config.dev.ts
  client/webpack/webpack.config.prod.ts
  client/yarn.lock
Labels: feature

#113 [feature/#112] 장바구니 배송비 추가
  client/src/pages/Cart.tsx
Labels: feature

#176 [feature/#131] <Redirect> 기능 추가
  client/src/lib/router/Redirect.tsx
  client/src/pages/ProductsPreview.tsx
Labels: feature

#177 [bugfix/#165] ZoomImage 마우스 벗어나도 있는 버그 수정
  client/src/components/ZoomImage/ZoomImage.tsx
Labels: bug

#182 [feature/#127-signup-api] 회원가입
  client/src/components/Signup/Password.tsx
  client/src/components/common/Address.tsx
  client/src/constants/message.ts
  client/src/constants/signup.ts
  client/src/pages/Signup/Signup.tsx
  client/src/styles/global-style.ts
  server/src/models/users/dto/create-user.dto.ts
  server/src/models/users/user.service.ts
Labels: feature

#185 [feature/#178-review-question] 상품, 사용자 review question API 작성
  server/seed/data/board.json
  server/seed/seeder/create-boards.seed.ts
  server/seed/version
  server/src/main.ts
  server/src/models/board/board.module.ts
  server/src/models/board/board.repository.ts
  server/src/models/board/board.service.ts
  server/src/models/board/dto/board-response.dto.ts
  server/src/models/board/dto/create-content.dto.ts
  server/src/models/board/entities/board-comment.entity.ts
  server/src/models/board/entities/board-content.entity.ts
  server/src/models/board/entities/board.entity.ts
  server/src/models/product/product.controller.ts
  server/src/models/product/product.module.ts
  server/src/models/product/product.service.ts
  server/src/models/users/user.controller.ts
  server/src/models/users/user.module.ts
Labels: feature

#184 [refactor/#183] category, search 지적사항 수정
  client/src/components/Nav/Category.tsx
  client/src/components/Nav/Search.tsx
Labels: refactor

#188 [feature/#178-notice] 공지사항 게시판 API 추가
  server/src/models/board/board.controller.ts
  server/src/models/board/board.repository.ts
  server/src/models/board/board.service.ts
  server/src/models/product/product.controller.ts
  server/src/models/users/user.controller.ts
Labels: feature, refactor

#192 [feature/#119] ELK docker-compose로 build
  server/.devcontainer/docker-compose.yml
  server/elk/elasticsearch/Dockerfile
  server/elk/elasticsearch/config/elasticsearch.yml
  server/elk/kibana/Dockerfile
  server/elk/kibana/config/kibana.yml
  server/elk/logstash/Dockerfile
  server/elk/logstash/config/logstash.yml
  server/elk/logstash/entrypoint.sh
  server/elk/logstash/pipeline/logstash.conf
  server/package.json
  server/yarn.lock
Labels: feature

#194 [feature/#175] board component 작성 & 상세페이지, 공지사항 적용
  client/src/App.tsx
  client/src/components/Board/Board.tsx
  client/src/components/Board/Modal.tsx
  client/src/components/Board/Table.tsx
  client/src/components/Board/index.ts
  client/src/components/Footer.tsx
  client/src/components/Nav/AuthBoxContent.tsx
  client/src/components/Pagination.tsx
  client/src/components/ProductContent.tsx
  client/src/components/Signin/LoginForm.tsx
  client/src/components/Sort.tsx
  client/src/constants/message.ts
  client/src/hooks/query/board/index.tsx
  client/src/hooks/query/users/index.ts
  client/src/pages/Notice.tsx
  client/src/pages/Product.tsx
  client/src/pages/ProductsPreview.tsx
  client/src/types/index.ts
  client/src/utils/board/index.ts
Labels: feature

#199 [feature/#198-edit-res] board api 반환 타입 변경 및 버그 수정
  client/src/components/Board/Board.tsx
  client/src/components/Board/Table.tsx
  client/src/types/index.ts
  server/src/models/board/board.repository.ts
  server/src/models/board/entities/board-comment.entity.ts
  server/src/models/board/entities/board-content.entity.ts
  server/src/models/users/entities/user.entity.ts
  server/src/models/users/user.controller.ts
Labels: bug, feature

#200 [feature/#198]: review, question 수정 삭제 api 추가
  server/src/models/board/board.repository.ts
  server/src/models/board/board.service.ts
  server/src/models/product/product.controller.ts
  server/src/models/users/user.controller.ts
Labels: feature

#202 [feature/#167] 데모 로그인 안내 추가
  client/src/components/Signin/LoginForm.tsx
Labels: feature

#201 [feature/#171] 상품 Count에 키보드 조작 추가, blur시 0이면 1 채우기
  client/src/components/common/Count.tsx
Labels: feature

#203 [feature/#195] mypage board
  client/src/App.tsx
  client/src/components/Board/Table.tsx
  client/src/components/Board/TableItem.tsx
  client/src/components/MyPage/Board.tsx
  client/src/components/MyPage/BoardProduct.tsx
  client/src/components/Sort.tsx
  client/src/hooks/query/board/index.tsx
  client/src/pages/MyPage/MyBoard.tsx
  client/src/types/index.ts
  client/src/utils/board/index.ts
Labels: feature

#208 [feature/#206] 검색 기능 및 스크립트 수정
  client/src/components/Nav/AutoComplete.tsx
  client/src/components/Nav/Search.tsx
  client/src/constants/message.ts
  client/src/hooks/query/products/index.tsx
  client/src/pages/ProductsPreview.tsx
  client/src/types/index.ts
  client/src/utils/product/index.ts
  elk/logstash/entrypoint.sh
  server/src/elastic/elastic.search.option.ts
  server/src/elastic/elastic.service.ts
  server/src/models/product/product.controller.ts
Labels: feature

#210 [bug/#209] 회원가입 에러 수정
  server/src/models/users/dto/create-user.dto.ts
Labels: bug

#214 [feature/#204] 수정 삭제 컴포넌트 기능 추가
  client/src/components/Board/Board.tsx
  client/src/components/Board/Modal.tsx
  client/src/components/Board/Table.tsx
  client/src/components/Board/TableItem.tsx
  client/src/components/MyPage/Board.tsx
  client/src/components/Nav/AuthBoxContent.tsx
  client/src/components/ProductContent.tsx
  client/src/constants/message.ts
  client/src/hooks/query/board/index.tsx
  client/src/pages/MyPage/MyBoard.tsx
  client/src/pages/Notice.tsx
  client/src/types/index.ts
  client/src/utils/board/index.ts
Labels: feature

#215 [feature/#189] like 기능
  client/src/components/common/HeartButton.tsx
  client/src/components/common/LikeButton.tsx
  client/src/hooks/query/products/index.tsx
  client/src/pages/Product.tsx
  server/@types/express/index.d.ts
  server/seed/version
  server/src/app.module.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.ts
  server/src/auth/decorators/for-admin.decorator.ts
  server/src/auth/decorators/for-user.decorator.ts
  server/src/auth/guards/jwt.guard.ts
  server/src/auth/guards/local.guard.ts
  server/src/auth/jwt.guard.ts
  server/src/auth/strategies/jwt.strategy.ts
  server/src/auth/strategies/local.strategy.ts
  server/src/models/board/board.controller.ts
  server/src/models/order/order.controller.ts
  server/src/models/product/dto/like.dto.ts
  server/src/models/product/dto/product-list-page.dto.ts
  server/src/models/product/entities/product.entity.ts
  server/src/models/product/product.controller.ts
  server/src/models/product/product.repository.ts
  server/src/models/product/product.service.ts
  server/src/models/users/entities/like.entity.ts
  server/src/models/users/entities/user.entity.ts
  server/src/models/users/user.controller.ts
  server/src/models/users/user.module.ts
Labels: feature

#219 [feature/#217] my-page style 통일
  client/src/App.tsx
  client/src/components/MyPage/MenuBar.tsx
  client/src/components/MyPage/MyPageLayout.tsx
  client/src/components/Nav/AuthBoxContent.tsx
  client/src/pages/MyPage/MyBoard.tsx
  client/src/pages/MyPage/MyLike.tsx
  client/src/pages/MyPage/MyPage.tsx
  client/src/pages/MyPage/MyPageConfirm.tsx
  client/src/pages/MyPage/MyPageEdit.tsx
  client/src/pages/MyPage/my-page-style.tsx
Labels: feature, refactor

#222 [feature/#197] side navigation bar
  client/src/App.tsx
  client/src/components/Nav/Category.tsx
  client/src/components/SNB/RecentProduct.tsx
  client/src/components/SNB/SNB.tsx
  client/src/components/SNB/Up.tsx
  client/src/components/SNB/index.ts
  client/src/pages/MyPage/MyBoard.tsx
  client/src/pages/Product.tsx
  client/src/types/index.ts
Labels: feature

#223 [feature/#207] oauth 로그인
  client/src/constants/message.ts
  client/src/pages/Signin.tsx
  client/src/pages/Signup/Signup.tsx
  client/src/pages/Signup/SignupMethod.tsx
  server/@types/express/index.d.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
  server/src/models/users/dto/create-user.dto.ts
  server/src/models/users/entities/user.entity.ts
  server/src/models/users/user.controller.ts
  server/src/models/users/user.service.ts
Labels: feature

#230 [feature/#224] 회원 정보 변경
  client/src/App.tsx
  client/src/components/MyPage/MenuBar.tsx
  client/src/components/Nav/AuthBoxContent.tsx
  client/src/pages/MyPage/MyPageConfirm.tsx
  client/src/pages/MyPage/MyPageEdit.tsx
  server/src/models/users/dto/update-user.dto.ts
  server/src/models/users/user.controller.ts
  server/src/models/users/user.repository.ts
  server/src/models/users/user.service.ts
Labels: feature

#231 [deploy] deploy 설정 변경
  docker-compose.yml
Labels: 미분류

#235 [refactoring/#227] 나의 주문목록 스타일
  client/src/components/MyPage/MenuBar.tsx
  client/src/components/MyPage/OrderStatusSelector.tsx
  client/src/components/Nav/AuthBoxContent.tsx
  client/src/components/Order/OrderPreview.tsx
  client/src/components/Order/OrderPreviewProduct.tsx
  client/src/hooks/query/orders/useTempOrders.tsx
  client/src/pages/MyPage/MyOrder.tsx
  client/src/pages/MyPage/my-page-style.tsx
  client/src/types/index.ts
  client/src/utils/orders/index.ts
  server/src/models/order/entities/order.entity.ts
  server/src/models/order/order.repository.ts
Labels: refactor

#237 [hotfix/jwt-guard] jwt-guard 수정
  server/src/auth/guards/jwt.guard.ts
Labels: hotfix

#247 [refactor/#246] form style, phone validation 수정
  client/src/pages/Order/Order.tsx
  client/src/pages/Order/style.tsx
Labels: feature, refactor

#248 [bugfix/#241] like 잘못찾는 버그 수정
  client/src/components/ProductList.tsx
  server/src/models/product/product.repository.ts
Labels: bug
